[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.3"
serde_json = "1.0.91"
tokio = { version = "1.24.2", features = ["full"] }
