//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gis_osm_pois_free_1")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gid: i32,
    pub osm_id: Option<String>,
    pub code: Option<i32>,
    pub fclass: Option<String>,
    pub name: Option<String>,
    pub geom: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
