//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: Option<String>,
    pub password: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


// Schema	数据库(Database)
// Entity	数据表及关系(Table and Relation)
// Model	数据表(Table)
// Relation	关系(Relation)
// Column	字段的定义
// PrimaryKey	主键(Primary key)
// Attribute	字段(Column)
// ActiveModel	可写操作
